{% set name = "datasets" %}
{% set version = "2.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c82458d635539b5a5dbed0fba8837006dfc3c213a5bcc00e18a67789f0f0f16f

build:
  noarch: python
  number: 0
  entry_points:
    - datasets-cli=datasets.commands.datasets_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiohttp
    - dill <0.3.7
    - fsspec >=2021.11.1
    - huggingface_hub >=0.2.0,<1.0.0
    - importlib-metadata
    - multiprocess
    - numpy >=1.17
    - packaging
    - pandas
    - pyarrow >=6.0.0
    - python >=3.6
    - python-xxhash
    - pyyaml >=5.1
    - requests >=2.19.0
    - responses <0.19
    - tqdm >=4.62.1

test:
  imports:
    - datasets
    - datasets.commands
    - datasets.features
    - datasets.filesystems
    - datasets.formatting
    - datasets.io
    - datasets.packaged_modules
    - datasets.tasks
    - datasets.utils
  commands:
    - pip check
    - datasets-cli --help
  requires:
    - pip

about:
  home: https://github.com/huggingface/datasets
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: HuggingFace/Datasets is an open library of NLP datasets.
  description: |
    Datasets is a lightweight library providing one-line dataloaders for many
    public datasets and one liners to download and pre-process any of the number
    of datasets major public datasets provided on the HuggingFace Datasets Hub.
    Datasets are ready to use in a dataloader for training/evaluating a ML model
    (Numpy/Pandas/PyTorch/TensorFlow/JAX). Datasets also provide an API for
    simple, fast, and reproducible data pre-processing for the above public
    datasets as well as your own local datasets in CSV/JSON/text.
  doc_url: https://huggingface.co/docs/datasets/
  dev_url: https://github.com/huggingface/datasets

extra:
  recipe-maintainers:
    - oblute
    - Tata17
    - thewchan
    - mxr-conda
