{% set name = "datasets" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 616412868b54479e59be4548edc196f5b55ad3872c3c364b4172052d0bdb1819

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - dill
    - multiprocess
    - numpy >=1.17
    - pandas
    - pyarrow >=0.17.1
    - python
    - requests >=2.19.0
    - tqdm >=4.27,<4.50.0
    - python-xxhash
    - dataclasses

test:
  imports:
    - datasets
    - datasets.commands
    - datasets.utils

about:
  home: https://github.com/huggingface/datasets
  license: Apache-2.0
  license_family: Apache
  # License file manually packaged. See: https://github.com/huggingface/datasets/pull/1007
  license_file: LICENSE
  summary: HuggingFace/Datasets is an open library of NLP datasets.
  doc_url: https://huggingface.co/docs/datasets/
  dev_url: https://github.com/huggingface/datasets

extra:
  recipe-maintainers:
    - oblute
    - Tata17
    - thewchan
